---
- name: Configuration VLAN, IP et Trunk sur switch Cisco
  hosts: switches
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Créer VLAN de gestion
      ios_config:
        lines:
          - name Management
        parents: vlan 100

    - name: Activer interface VLAN 100 et lui attribuer une IP
      ios_config:
        lines:
          - ip address 192.168.100.1 255.255.255.0
          - no shutdown
        parents: interface vlan 100

    - name: Configurer l'interface GigabitEthernet1/0/1 en trunk
      ios_config:
        lines:
          - switchport mode trunk
        parents: interface GigabitEthernet1/0/1
